# Setup
title:        It's more fun to compute
tagline:      Thoughts on maths and computing
description:  "A blog exploring how python and linux can be used to aid academic research."
url:          "https://jwalton3141.github.io/"
baseurl:      ""
paginate:     1
# Don't include date in url - doesn't add any useful info.
permalink: /:title/

# About/contact
author:
  name:       Jack Walton
  url:        https://jwalton3141.github.io/about

#Others
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
