# Setup
title:        It's more fun to compute
tagline:      Thoughts on maths and computing
description:  "A blog exploring topics on Data Science, Data Engineering and Computing."
url:          "https://jwalton3141.github.io/"
baseurl:      ""
paginate:     1
# Don't include date in url - doesn't add any useful info.
permalink: /:title/
# Include posts even if date is set in future
future: true

# About/contact
author:
  name:       Jack Walton
  url:        https://jwalton3141.github.io/about

collections:
  talks:
    output: true
  teaching:
    output: true

#Others
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
